version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./.dbdata/db:/var/lib/mysql"
    restart: "no"
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    depends_on:
      - db
    image: developez/apache-php:7.1 # SE PUEDE USAR UNA IMAGEN COMPILADA
    # build: . # SE PUEDE COMPILAR LA PRIMERA VEZ
    links:
      - db
    ports:
      - "80:80"
    restart: "no"
    volumes:
      - ./wordpress:/var/www/html/wordpress/
      - ./apache2/apache2.conf:/etc/apache2/apache2.conf
      - ./apache2/wordpress.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./php/php.ini:/etc/php/7.1/apache2/php.ini
      - ./php/php.ini:/etc/php/7.1/cli/php.ini
      # - ./docker/start.sh:/usr/local/bin/start.sh PODEMOS VINCULAR MODIFICACION DEL SCRIPT
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_PREFIX: ${MYSQL_PREFIX}
      WORDPRESS_VERSION: ${WORDPRESS_VERSION}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "8080:80"
    restart: "no"
